name 'chef_server'
maintainer 'Satyajit Roy'
maintainer_email 'email2sroy@gmail.com'
license 'all_rights'
description 'Installs/Configures chef_server'
long_description 'Installs/Configures chef_server'
version '0.1.1'
